### ISSUE TITLE
[Harem][UI][System] Double climax icon persists and then is hidden

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#489]
**Describe the bug**
The Double climax button is hidden on a certain case. The button remains hidden until the user aborts experiment and starts a new one.

**To Reproduce**
1. Go to Harem Lobby
2. Select an experiment with the "Cum Outside" "Cum Inside" buttons greyed out during the start of the experiment. (Used Alet x Dreamer - Threesome Arm Held Spitroast)
3. Achieve Near Max Ecstacy for both Dreamer and Alet.
4. The "Cum Inside" button should now flip over and reveal the Double Climax button (2 hearts icon) and active
5. Let Alet Climax without pressing any button
6. Her Ecstasy should now decrease.
7. Observe the buttons: Dreamer now has only the "Cum Outside" button available to click, with the Double Climax button still visible, but greyed out. The Cum Inside button remains hidden
8. Pause the animation, and restart the animation.
9. Both Cum Outside/Inside buttons are now available
10. In the same session, get Alet and Dreamer to near Max Ecstasy to reveal the Double Climax button
11. Observe: Cum Outside/Inside button remains on screen and active, but no Double Climax.

**Expected behavior**
Case 1: When both parties at near max ecstasy is achieved and the partner climaxes after reaching max ecstasy, both cum in/out buttons should be available again.
Case 2: When both parties at near max ecstasy is achieved, the double climax button should always be available.

**Screenshots**
Will try and provide a recording if the above description is insufficient. 

Game Version: **0.4.7**

**Comment by Panthear** [comment]
I have the screenshot, as I just wanted to post the same problem... but you beat me (again):

![grafik](https://user-images.githubusercontent.com/95415732/149398124-5f8ccad1-f0f9-451b-9e85-f36158b515f8.png)

I personally think this is somwhat connected to this issue #399 , as this happens especially when this is in close succession after a climax (and the user then doesn't count).

**Comment by poykun** [comment]
I think one part of the issue is fixed in 0.4.9.  The double climax no longer persists, but it is not visible in the same session when achieving Ecstacy for both parties. I'll test again to check at a later time.

**Comment by PuffyVulva** [comment]
issue still here !
Game version 0.7.0

![lovecraft bug 2](https://user-images.githubusercontent.com/54502195/229331945-5fcb85a9-a4dc-4808-8e60-43b1d075abe1.jpg)
