### ISSUE TITLE
[Model] Anya Ribbon Outfit

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#8]
![unknown](https://user-images.githubusercontent.com/11155504/143678665-d2bb21ab-8c6d-4ba8-9bb0-2a8af602aff8.png)

COMMONLY REPORTED texture issue on Anya's ribbon/present outfit

**Comment by ombra1501** [comment]
fixed

**Comment by Cryshah** [comment]
not fixed
![image](https://user-images.githubusercontent.com/95218688/143853266-4069d8df-e121-452b-8554-22c9deced366.png)

**Comment by Awfulwaffle1** [comment]
Current iteration of Gallery does not have Holiday costume available for use. Closing.
