### ISSUE TITLE
INTERFACE - Fast clicking the like button causes the expandable tab under player names to close

### ISSUE THREAD

**Issue by Bl4cktalon** [itsamewayu/OLFallenDoll#998]
INTERFACE - Fast clicking the like button causes the expandable tab under player names to close

And this bug is a fresh one, just after last update. Forces one to make pauses between sending likes and check how many likes you've actually managed to send.

https://gyazo.com/2b7f2d9731c7c521e2d239dbb7c17a5e

**Comment by Awfulwaffle1** [comment]
@Bl4cktalon I'll let you sign off on this one. I'm thinking it's resolved as of 0.7.75b.
The selected player frame on the playerlist no longer closes from its expanded state UNLESS the user
- hovers out of the playlist area
- the player clicks to expand another name

**Comment by Bl4cktalon** [comment]
Not quite resolved. I rather have noticed it evolved in a different issue:
Now after you send a few likes to a player. Like around ~3 of those you often find and that subsequent clicking of the [LIKE] button has no effect anymore. Then you have to move the cursor away from the [LIKE] button and then place it back to be able to click and send further likes.

Also a question: What's up with the limit at which the likes are being able to be sent to a player now (compared to prior to the 2 last patches)? Has it been intentionally throttled down or is a result of a bug?

**Comment by Awfulwaffle1** [comment]
@Bl4cktalon I think this is as designed, but only the devs or @77007 can address your inquiry above.
Though, would you say that original issue has been resolved?
